-- CreateTable
CREATE TABLE "events" (
    "Identifiant" BIGINT NOT NULL,
    "Titre - FR" TEXT,
    "Chapô - FR" TEXT,
    "Description longue - FR" TEXT,
    "Permalien" TEXT,
    "Mots clés - FR" TEXT,
    "Résumé horaires - FR" TEXT,
    "Horaires ISO" TEXT,
    "Horaires détaillés - FR" TEXT,
    "Première date - FR" TEXT,
    "Dernière date - FR" TEXT,
    "Conditions de participation, tarifs - FR" TEXT,
    "Accessibilité - FR" TEXT,
    "Création de la fiche - FR" TEXT,
    "Dernière mise à jour - FR" TEXT,
    "Image" TEXT,
    "Lien d'accès" TEXT,
    "Outils d'inscription" TEXT,
    "En une" TEXT,
    "Âge du public ciblé" TEXT,
    "Statut" TEXT,
    "Crédits" TEXT,
    "Type d'événement" TEXT,
    "Etiquette" TEXT,
    "Détail des tarifs" TEXT,
    "Mode de participation" TEXT,
    "Lieu: Identifiant" BIGINT,
    "Lieu: Nom" TEXT,
    "Lieu: Adresse" TEXT,
    "Lieu: Région" TEXT,
    "Lieu: Département" TEXT,
    "Lieu: Ville" TEXT,
    "Lieu: Arrondissement" TEXT,
    "Lieu: Quartier" TEXT,
    "Lieu: Code postal" TEXT,
    "Lieu: Code INSEE" TEXT,
    "Lieu: Latitude" DOUBLE PRECISION,
    "Lieu: Longitude" DOUBLE PRECISION,
    "Lieu: Description - FR" TEXT,
    "Lieu: Site internet" TEXT,
    "Lieu: Accès - FR" TEXT,
    "Label" TEXT,
    "État" TEXT,

    CONSTRAINT "events_pkey" PRIMARY KEY ("Identifiant")
);
